// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// UpdateUserCoins provides a mock function with given fields: ctx, senderID, amount
func (_m *Storage) UpdateUserCoins(ctx context.Context, senderID string, amount int) error {
	ret := _m.Called(ctx, senderID, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserCoins")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, senderID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_UpdateUserCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserCoins'
type Storage_UpdateUserCoins_Call struct {
	*mock.Call
}

// UpdateUserCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID string
//   - amount int
func (_e *Storage_Expecter) UpdateUserCoins(ctx interface{}, senderID interface{}, amount interface{}) *Storage_UpdateUserCoins_Call {
	return &Storage_UpdateUserCoins_Call{Call: _e.mock.On("UpdateUserCoins", ctx, senderID, amount)}
}

func (_c *Storage_UpdateUserCoins_Call) Run(run func(ctx context.Context, senderID string, amount int)) *Storage_UpdateUserCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Storage_UpdateUserCoins_Call) Return(_a0 error) *Storage_UpdateUserCoins_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_UpdateUserCoins_Call) RunAndReturn(run func(context.Context, string, int) error) *Storage_UpdateUserCoins_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
