// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Merch struct {
	ID        string             `db:"id"`
	Name      string             `db:"name"`
	Price     int32              `db:"price"`
	CreatedAt time.Time          `db:"created_at"`
	UpdatedAt time.Time          `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type Purchase struct {
	ID        string    `db:"id"`
	UserID    string    `db:"user_id"`
	MerchID   string    `db:"merch_id"`
	CreatedAt time.Time `db:"created_at"`
}

type Transaction struct {
	ID                string      `db:"id"`
	SenderID          string      `db:"sender_id"`
	ReceiverID        pgtype.Text `db:"receiver_id"`
	TransactionTypeID int32       `db:"transaction_type_id"`
	Amount            int32       `db:"amount"`
	CreatedAt         time.Time   `db:"created_at"`
}

type TransactionType struct {
	ID    int32  `db:"id"`
	Title string `db:"title"`
}

type User struct {
	ID           string             `db:"id"`
	Username     string             `db:"username"`
	PasswordHash string             `db:"password_hash"`
	Balance      int32              `db:"balance"`
	CreatedAt    time.Time          `db:"created_at"`
	UpdatedAt    time.Time          `db:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at"`
}
