// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddToInventory(ctx context.Context, arg AddToInventoryParams) error
	GetMerchByName(ctx context.Context, name string) (GetMerchByNameRow, error)
}

var _ Querier = (*Queries)(nil)
