DROP TABLE IF EXISTS purchases CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS transaction_types CASCADE;
DROP TABLE IF EXISTS merch CASCADE;
DROP TABLE IF EXISTS users CASCADE;