// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByName(ctx context.Context, username string) (GetUserByNameRow, error)
	GetUserInfoByID(ctx context.Context, id string) (GetUserInfoByIDRow, error)
	GetUserInfoByUsername(ctx context.Context, username string) (GetUserInfoByUsernameRow, error)
}

var _ Querier = (*Queries)(nil)
