// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetReceivedTransactions(ctx context.Context, receiverID pgtype.Text) ([]GetReceivedTransactionsRow, error)
	// only coin transfers
	GetSentTransactions(ctx context.Context, senderID string) ([]GetSentTransactionsRow, error)
	GetUserBalanceByID(ctx context.Context, id string) (GetUserBalanceByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	// only coin transfers
	GetUserIDByUsername(ctx context.Context, username string) (string, error)
	GetUserInventory(ctx context.Context, userID string) ([]GetUserInventoryRow, error)
}

var _ Querier = (*Queries)(nil)
