// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rshelekhov/merch-store/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MerchManager is an autogenerated mock type for the MerchManager type
type MerchManager struct {
	mock.Mock
}

type MerchManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MerchManager) EXPECT() *MerchManager_Expecter {
	return &MerchManager_Expecter{mock: &_m.Mock}
}

// AddToInventory provides a mock function with given fields: ctx, userID, merchID
func (_m *MerchManager) AddToInventory(ctx context.Context, userID string, merchID string) error {
	ret := _m.Called(ctx, userID, merchID)

	if len(ret) == 0 {
		panic("no return value specified for AddToInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, merchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MerchManager_AddToInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToInventory'
type MerchManager_AddToInventory_Call struct {
	*mock.Call
}

// AddToInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - merchID string
func (_e *MerchManager_Expecter) AddToInventory(ctx interface{}, userID interface{}, merchID interface{}) *MerchManager_AddToInventory_Call {
	return &MerchManager_AddToInventory_Call{Call: _e.mock.On("AddToInventory", ctx, userID, merchID)}
}

func (_c *MerchManager_AddToInventory_Call) Run(run func(ctx context.Context, userID string, merchID string)) *MerchManager_AddToInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MerchManager_AddToInventory_Call) Return(_a0 error) *MerchManager_AddToInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MerchManager_AddToInventory_Call) RunAndReturn(run func(context.Context, string, string) error) *MerchManager_AddToInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchByName provides a mock function with given fields: ctx, itemName
func (_m *MerchManager) GetMerchByName(ctx context.Context, itemName string) (entity.Merch, error) {
	ret := _m.Called(ctx, itemName)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchByName")
	}

	var r0 entity.Merch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Merch, error)); ok {
		return rf(ctx, itemName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Merch); ok {
		r0 = rf(ctx, itemName)
	} else {
		r0 = ret.Get(0).(entity.Merch)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, itemName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MerchManager_GetMerchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchByName'
type MerchManager_GetMerchByName_Call struct {
	*mock.Call
}

// GetMerchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - itemName string
func (_e *MerchManager_Expecter) GetMerchByName(ctx interface{}, itemName interface{}) *MerchManager_GetMerchByName_Call {
	return &MerchManager_GetMerchByName_Call{Call: _e.mock.On("GetMerchByName", ctx, itemName)}
}

func (_c *MerchManager_GetMerchByName_Call) Run(run func(ctx context.Context, itemName string)) *MerchManager_GetMerchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MerchManager_GetMerchByName_Call) Return(_a0 entity.Merch, _a1 error) *MerchManager_GetMerchByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MerchManager_GetMerchByName_Call) RunAndReturn(run func(context.Context, string) (entity.Merch, error)) *MerchManager_GetMerchByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMerchManager creates a new instance of MerchManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchManager {
	mock := &MerchManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
