// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: coins.sql

package sqlc

import (
	"context"
)

const updateUserCoins = `-- name: UpdateUserCoins :exec
UPDATE users
SET
    balance = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserCoinsParams struct {
	ID      string `db:"id"`
	Balance int32  `db:"balance"`
}

func (q *Queries) UpdateUserCoins(ctx context.Context, arg UpdateUserCoinsParams) error {
	_, err := q.db.Exec(ctx, updateUserCoins, arg.ID, arg.Balance)
	return err
}
