// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	RegisterCoinTransfer(ctx context.Context, arg RegisterCoinTransferParams) error
	UpdateUserCoins(ctx context.Context, arg UpdateUserCoinsParams) error
}

var _ Querier = (*Queries)(nil)
